cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns =[
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='shop:main_page', permanent=False)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^testimonial/', include('testimonials.urls', namespace='testimonials')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from shop import views


urlpatterns = [
    url(r'^$', views.mainPage, name='main_page'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<cateogry_slug>[-\w]+)/$', views.product_list,
        name='product_list_by_cateogry'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),

]

testimonials/urls.py
from django.conf.urls import url
from testimonials import views


urlpatterns = [
    url(r'^$', views.read_and_write_testimonial, name='testimonial_list'),

]

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.functional import lazy
from PIL import Image
from django.contrib.postgres.fields import HStoreField

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from decimal import Decimal

# Create your models here.
class Cateogry(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(db_index=True, unique=True)

    class Meta:
        ordering =   ['name']
        verbose_name = 'cateogry'
        verbose_name_plural = 'cateogries'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_cateogry', args=[self.slug])

    def save(self, *args, **kwargs):
        for field_name in ['name',]:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(Cateogry, self).save(*args, **kwargs)


class Product(models.Model):
    cateogry = models.ForeignKey('Cateogry', related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [('id', 'slug')]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class Attribute(models.Model):
    product = models.ForeignKey('Product', related_name="patt")
    weight = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    waist_size = models.PositiveSmallIntegerField(blank=True, null=True)
    size = models.CharField(max_length=2, blank=True, null=True)

    def clean(self, *args, **kwargs):
        super(Attribute, self).clean(*args, **kwargs)
        if self.weight == Decimal('0.350'):
            raise ValidationError({'weight': _('Cannot use this value')})

    class Meta:
        unique_together = ('product', 'weight')

shop/views.py
from django.shortcuts import render, get_object_or_404
from shop.models import Cateogry, Product, Attribute
from cart.forms import CartAddProductForm
from testimonials.models import Testimonial_


# Create your views here.
def product_list(request, cateogry_slug=None):
    cateogry = None
    cateogries = Cateogry.objects.all()
    testimonials = Testimonial_.objects.all()[:5]
    products = Product.objects.filter(available=True)
    if cateogry_slug:
        cateogry = get_object_or_404(Cateogry,slug=cateogry_slug)
        products = products.filter(cateogry=cateogry)
    return render(request, 'shop/product/list.html', {
        'cateogry': cateogry,
        'cateogries': cateogries,
        'products': products,
        'testimonials':testimonials,
    })


def product_detail(request, id, slug):

    product = get_object_or_404(Product, id=id,
                                     slug=slug,
                                     available=True)
    product_attributes = product.patt.all()
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'product_attributes': product_attributes,})


def mainPage(request):
    cateogries = Cateogry.objects.all()
    return render(request, 'shop/product/main.html', {'cateogries': cateogries, } )

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title> {% block title%}
    {% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet"> 


    <script src="https://use.fontawesome.com/e3e69968e1.js"></script>

    <!-- Bootstrap core CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <!-- Bootstrap Theme -->

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/readable/bootstrap.min.css"> 
    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/navbar-fixed-top.css' %}">


    <!-- css for drop down menu -->
    <link rel="stylesheet" href="{% static 'css/navbar-element.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
    

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/carousel.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <style>
  

    body {
      font-family: 'Open Sans', sans-serif;
    }
 
  .content {
      padding-top: 30px;
  }

  /* Testimonials */
  .testimonials blockquote {
      background: #f8f8f8 none repeat scroll 0 0;
      border: medium none;
      color: #666;
      display: block;
      font-size: 14px;
      line-height: 20px;
      padding: 15px;
      position: relative;
  }
  .testimonials blockquote::before {
      width: 0; 
      height: 0;
    right: 0;
    bottom: 0;
    content: " "; 
    display: block; 
    position: absolute;
      border-bottom: 20px solid #fff;    
    border-right: 0 solid transparent;
    border-left: 15px solid transparent;
    border-left-style: inset; /*FF fixes*/
    border-bottom-style: inset; /*FF fixes*/
  }
  .testimonials blockquote::after {
      width: 0;
      height: 0;
      right: 0;
      bottom: 0;
      content: " ";
      display: block;
      position: absolute;
      border-style: solid;
      border-width: 20px 20px 0 0;
      border-color: #e63f0c transparent transparent transparent;
  }
  .testimonials .carousel-info img {
      border: 1px solid #f5f5f5;
      border-radius: 50px ;
      height: 25px;
      padding: 3px;
      width: 75px;
  }
  .testimonials .carousel-info {
      overflow: hidden;
  }
  .testimonials .carousel-info img {
      margin-right: 15px;
  }
  .testimonials .carousel-info span {
      display: block;
  }
  .testimonials span.testimonials-name {
      color: #e6400c;
      font-size: 16px;
      font-weight: 300;
      margin: 23px 0 7px;
  }
  .testimonials span.testimonials-post {
      color: #656565;
      font-size: 12px;
  }






.dropdown:hover .dropdown-menu {
    display: block;
    margin-top:0;

  }  

  </style>


  </head>

  <body>

    <!-- Fixed navbar -->

    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://admis.hp.nic.in/hpprisons/"><img class="img-responsive" src="{% static 'img/hpj-logo.png' %}"></a>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'shop:main_page' %}" style="font-family: 'Oswald', sans-serif;"><span class="glyphicon glyphicon-home"></span>  Home</a></li>
            <li class="active dropdown">
              <a href="/" class="dropdown-toggle" data-toggle="dropdown" style="font-family: 'Oswald', sans-serif;">Products <span class="caret"></span></a>
               
                <ul class="dropdown-menu multi-column columns-2">
                  <div class="row">
                    <div class="col-sm-6">
                      <ul class="multi-column-dropdown">
                        <li><img class="img-responsive center-block" src="{% static 'img/bakery.jpg' %}" style="width:100px"></li>
                        {% for p in bakery_items %}
                          
                         <li>
                              <a href="{{ p.get_absolute_url }}">{{ p.name }}</a>
                              
                         </li>
                          
                        {% endfor %}

                      </ul>
                    </div>
                    <div class="col-sm-6">
                      <ul class="multi-column-dropdown">
                        <li><img class="img-responsive center-block" src="{% static 'img/handicraft.png' %}" style="width:100px"></li>
                          {% for p in handicraft_items %}
                                  
                                 <li>
                                      <a href="{{ p.get_absolute_url }}">{{ p.name }}</a>
                                      
                                 </li>
                                  
                          {% endfor %}
                      </ul>
                    </div>
                    
                  </div>
                </ul>

            </li>

            <li><a href="#about" style="font-family: 'Oswald', sans-serif;">About</a></li>
            <li><a href="#contact" style="font-family: 'Oswald', sans-serif;">Contact</a></li>
                        
          </ul>
          <ul class="nav navbar-nav navbar-right">
            
            <li class="active" style="padding-top: 10px;">
                   <div>
            {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Your cart:
                <a href="{% url 'cart:cart_detail' %}" class="bg-primary" >
                {{ total_items }} item{{ total_items|pluralize }},
                Rs. {{ cart.get_total_price }}
                </a>
             {% else %}
                Your Cart is empty
            {% endif %}
                
            {% endwith %}

        </div>
        
            </li>
            <li style="padding-left: 10px;"> 
            <div>
             <a class="navbar-brand" href="{% url 'shop:main_page' %}" ><img src="{% static 'img/pahal-logo.png' %}"></a>
            </div>
            </li>
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>
        <div class="container">
          <div class="text-center center-block" style="font-family: 'Indie Flower', cursive;">
          <h3>"Every rupee spent by you will be used for welfare of inmates"</h3>    
          </div>
        </div>
   
    <div class="container-fluid" style="padding-bottom:10px;">
      <div class="row">
        {% block sidebar %}
          
        {% endblock sidebar %}
        {% block carousel %}
           
        {% endblock %}
      </div>
    </div>

    {% block topseller %}

      
    {% endblock topseller %}

    {% block recommendations %}
      
    {% endblock recommendations %}

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>


    </div> <!-- /container -->
<link href="https://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
    <div class="container">
      <div class="row">
        .
      </div>
    </div>

<!--footer start from here-->
<footer>
  <div class="container-fluid" >
    <div class="row bg-primary">
      <div class="col-md-2"></div>
      <div class="col-md-2 col-sm-6 paddingtop-bottom">
        <h6 class="heading7">Contact Us</h6>
        <ul class="footer-ul">
          <li><a href="{% url 'testimonials:testimonial_list' %}"> Consumer Feedback</a></li>
          <li><a href="#"> Complaint Policy</a></li>
          <li><a href="#"> Suppliers / Our Offices</a></li>
          <li><a href="#"> Frequently Ask Questions</a></li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-6 paddingtop-bottom">
        <h6 class="heading7">Policies</h6>
        <div class="footer-ul">
          <li><a href="#"> Quality Program</a></li>
          <li><a href="#"> Refund Policy</a></li>
          <li><a href="#"> Privacy Policy</a></li>
          <li><a href="#"> Terms of Use</a></li>
          
        </div>
      </div>
      <div class="col-md-5 col-sm-6 paddingtop-bottom">
        <div class="fb-page" data-href="https://www.facebook.com/Himachal-Prisons-127010517681628" data-tabs="timeline" data-height="300" data-small-header="false" style="margin-bottom:15px;" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
          <div class="fb-xfbml-parse-ignore">
            <blockquote cite="https://www.facebook.com/Himachal-Prisons-127010517681628"><a href="https://www.facebook.com/Himachal-Prisons-127010517681628">Facebook</a></blockquote>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<!--footer start from here-->

<div class="copyright">
  <div class="container">
    <div class="col-md-12">
      <p>© 2016 - All Rights with Himachal Pradesh Prisons & Correctional Services Department.</p>
    </div>
  </div>
</div>



      <!-- facebook share -->
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>

      <!-- end facebook share -->

  </body>
</html>

shop/templates/shop/carousel.html
{% load static %} 
    <div class="col-md-6">
      
            <div id="myCarousel1" class="carousel slide vertical " data-ride="carousel" >
              <!-- Indicators -->
              <ol class="carousel-indicators" style="margin-bottom:-15px;">
                <li data-target="#myCarousel1" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel1" data-slide-to="1"></li>
                <li data-target="#myCarousel1" data-slide-to="2"></li>
                <li data-target="#myCarousel1" data-slide-to="3"></li>
                <li data-target="#myCarousel1" data-slide-to="4"></li>
              </ol>

              <!-- Carousel items -->
              <div class="carousel-inner">
                <div class="active item">
                  <img class="center-block img-responsive" src="{% static "img/bakery_1.jpg" %}" style="max-height: 400px;">
                  <div class="carousel-caption" style="margin-bottom:-43px;">
                  <h3>Bakery Products</h3>
                  <p >Bakery Items being produced at MC Jail Kanda</p>
                </div>
                </div>
                <div class="item">
                  <img class="center-block img-responsive" src="https://scontent.fmaa1-2.fna.fbcdn.net/v/t1.0-9/13716087_257966447919367_3662107450188509727_n.jpg?oh=e2ae8533940efccea56af5ab02edc8ee&oe=58F8347C"  style="max-height: 400px;" >
                  <div class="carousel-caption" style="margin-bottom:-43px;">
                  <h3>Pahal at Gaiety</h3>
                  <p>DG Prisons & Correctional Services at Gaiety Theater inspecting the sale of Pahal Store Items</p>
                </div>                
                </div>                
                <div class="item">
                  <img class="center-block img-responsive" src="https://scontent-sin6-1.xx.fbcdn.net/v/t1.0-9/13895213_270327056683306_1505730398655163860_n.jpg?oh=45f07a4f958bee0043bac43c6e81a22d&oe=58B1EC85" style="max-height: 400px;">
                  <div class="carousel-caption" style="margin-bottom:-43px;">
                  <h3>Bakery Store</h3>
                  <p>Pahal Store near District Jail Kaithu</p>
                </div>
                </div>
                <div class="item">
                  <img class="center-block img-responsive" src="https://scontent-sin6-1.xx.fbcdn.net/v/t1.0-9/12654500_150613348654678_9034199449786781696_n.jpg?oh=0ba7db75b783b4c246a9019acd495455&oe=58F6CA69" style="max-height: 400px;">
                  <div class="carousel-caption" style="margin-bottom:-43px;">
                  <h3>Dairy Farming</h3>
                  <p>A Dairy Farm at MC Jail Nahan managed my prison inmates</p>
                </div>
                </div>
                <div class="item">
                  <img class="center-block img-responsive" src="https://scontent-sin6-1.xx.fbcdn.net/v/t1.0-9/12644678_136770223372324_6688254722545411958_n.jpg?oh=99d07c7b4e2d6b186e2afa598c273d51&oe=58EE3D56" style="max-height: 400px;">
                  <div class="carousel-caption" style="margin-bottom:-43px;">
                  <h3>Handlooms</h3>
                  <p>A Tailoring Unit at MC Jail Nahan</p>
                </div>
                </div>

              </div>
              <!-- Carousel nav -->
              <a class="carousel-control left " href="#myCarousel1" data-slide="prev">&lsaquo;</a>
              <a class="carousel-control right " href="#myCarousel1" data-slide="next">&rsaquo;</a>
            </div>
    </div>

          <div class="col-md-3 col-sm-6 paddingtop-bottom">
        <div class="fb-page" data-href="https://www.facebook.com/Himachal-Prisons-127010517681628" data-tabs="timeline" data-height="300" data-small-header="false" style="margin-bottom:15px;" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
          <div class="fb-xfbml-parse-ignore">
            <blockquote cite="https://www.facebook.com/Himachal-Prisons-127010517681628"><a href="https://www.facebook.com/Himachal-Prisons-127010517681628">Facebook</a></blockquote>
          </div>
        </div>
      </div>

shop/templates/shop/recommendation_carousel.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/recommendation_carousel.css' %}">



<div class="container-fluid">
  <div class="row" >
    <div class="col-md-12">
      <div class="row panel panel-info" >
        <div class="panel-heading">
          <div class="panel-title">Recommended for you</div>
        </div>
        <div class="panel-body">   
            <div class="carousel carousel-showmanymoveone slide" id="carousel123">
              <div class="carousel-inner">

                {% for product in handicraft_items|slice:":1" %}
                  <div class="item active">
                  <div class="col-xs-12 col-sm-6 col-md-3 panel panel-default">
                      {% load thumbnail %}
                      {% thumbnail product.image "120" as im %}
                      <a href="{{ product.get_absolute_url }}">
                        <img class="center-block img-responsive " src="{% if im %}{{ im.url }}
                        {% else %}{% static "img/no_image.png" %}{% endif %}" alt="..."
                        >
                      </a>
                      {% endthumbnail %}
                      <p class="text-center" style="padding-top:10px;"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
                      <p class="text-center" >
                      <span class="badge">Rs. {{ product.price }}</span>
                      </p>                               
                  </div>
                </div>
                  
                {% endfor %}
                {% for product in handicraft_items|slice:"1:3" %}
                  <div class="item">
                  <div class="col-xs-12 col-sm-6 col-md-3 panel panel-default">
                      {% load thumbnail %}
                      {% thumbnail product.image "120" as im %}
                      <a href="{{ product.get_absolute_url }}">
                        <img class="center-block img-responsive " src="{% if im %}{{ im.url }}
                        {% else %}{% static "img/no_image.png" %}{% endif %}" alt="..."
                        >
                      </a>
                      {% endthumbnail %}
                      <p class="text-center" style="padding-top:10px;"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
                      <p class="text-center" >
                      <span class="badge">Rs. {{ product.price }}</span>
                      </p>                              
                  </div>
                </div>
                  
                {% endfor %}
                {% for product in bakery_items|slice:":3" %}
                  <div class="item">
                  <div class="col-xs-12 col-sm-6 col-md-3 panel panel-default " >
                      {% load thumbnail %}
                      {% thumbnail product.image "120" as im %}
                      <a href="{{ product.get_absolute_url }}">
                        <img class="center-block img-responsive " src="{% if im %}{{ im.url }}
                        {% else %}{% static "img/no_image.png" %}{% endif %}" alt="..."
                        >
                      </a>
                      {% endthumbnail %}
                      <p class="text-center" style="padding-top:10px;"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
                      <p class="text-center" >
                      <span class="badge">Rs. {{ product.price }}</span>
                      </p>
                  </div>
                </div>
                  
                {% endfor %}


              </div>
              <a class="left carousel-control" href="#carousel123" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
              <a class="right carousel-control" href="#carousel123" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
            </div>
        </div>
      </div>
    </div>
  </div>
  
</div>
<script src="{% static 'js/recommendation_carousel.js' %}"></script>

shop/templates/shop/sidebar.html
		<div class="col-md-3" style="padding-top: 30px;">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"> <i class="fa fa-birthday-cake" aria-hidden="true"></i>
                            Bakery</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">

                            	{% for item in bakery_items %}
                            		<tr>
                            				<td>
                            					<a href="{{ item.get_absolute_url }}">{{ item.name }} <span class="label label-success">Rs. {{ item.price }}</span></a>
                            				</td>
                            		</tr>
                            	{% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><i class="fa fa-shirtsinbulk" aria-hidden="true"></i>
                            Clothes / Handicraft </a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                            	{% for item in handicraft_items %}
                            		<tr>
                            				<td>
                            					<a href="{{ item.get_absolute_url }}">{{ item.name }} <span class="label label-success">Rs. {{ item.price }}</span></a>
                            				</td>
                            		</tr>
                            	{% endfor %}
                            </table>
                        </div>
                    </div>
                </div>

    
            </div>
		</div>

shop/templates/shop/topseller.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/topseller.css' %}">



{% load thumbnail %}
{% thumbnail image.image "300" as im %}
<a href="{{ image.image.url }}">
<img src="{{ im.url }}" class="image-detail">
</a>
{% endthumbnail %}



<div class="container-fluid">
  <div class="row" >
    <div class="col-md-12">
      <div class="row panel panel-info" >
        <div class="panel-heading">
          <div class="panel-title">Top Seller </div>
        </div>
        <div class="panel-body">   
            <div class="carousel carousel-topseller slide" id="carousel_topseller">
              <div class="carousel-inner">

                {% for product in bakery_items|slice:":1" %}
                  <div class="item active">
                  <div class="col-xs-12 col-sm-6 col-md-3 panel panel-default">
                      {% load thumbnail %}
                      {% thumbnail product.image "120" as im %}
                      <a href="{{ product.get_absolute_url }}">
                        <img class="center-block img-responsive " src="{% if im %}{{ im.url }}
                        {% else %}{% static "img/no_image.png" %}{% endif %}" alt="..."
                        >
                      </a>
                      {% endthumbnail %}
                      <p class="text-center" style="padding-top:10px;"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
                      <p class="text-center" >
                      <span class="badge">Rs. {{ product.price }}</span>
                      </p>                               
                  </div>
                </div>
                  
                {% endfor %}
                {% for product in bakery_items|slice:"1:3" %}
                  <div class="item">
                  <div class="col-xs-12 col-sm-6 col-md-3 panel panel-default">
                      {% load thumbnail %}
                      {% thumbnail product.image "120" as im %}
                      <a href="{{ product.get_absolute_url }}">
                        <img class="center-block img-responsive " src="{% if im %}{{ im.url }}
                        {% else %}{% static "img/no_image.png" %}{% endif %}" alt="..."
                        >
                      </a>
                      {% endthumbnail %}
                      <p class="text-center" style="padding-top:10px;"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
                      <p class="text-center" >
                      <span class="badge">Rs. {{ product.price }}</span>
                      </p>                              
                  </div>
                </div>
                  
                {% endfor %}
                {% for product in handicraft_items|slice:":3" %}
                  <div class="item">
                  <div class="col-xs-12 col-sm-6 col-md-3 panel panel-default " >
                      {% load thumbnail %}
                      {% thumbnail product.image "120" as im %}
                      <a href="{{ product.get_absolute_url }}">
                        <img class="center-block img-responsive " src="{% if im %}{{ im.url }}
                        {% else %}{% static "img/no_image.png" %}{% endif %}" alt="..."
                        >
                      </a>
                      {% endthumbnail %}
                      <p class="text-center" style="padding-top:10px;"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
                      <p class="text-center" >
                      <span class="badge">Rs. {{ product.price }}</span>
                      </p>
                  </div>
                </div>
                  
                {% endfor %}


              </div>
              <a class="left carousel-control" href="#carousel_topseller" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
              <a class="right carousel-control" href="#carousel_topseller" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
            </div>
        </div>
      </div>
    </div>
  </div>
  
</div>
<script src="{% static 'js/topseller.js' %}"></script>